dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
env:
  global:
  - secure: IhdbuzDS0zFqnUtm1k6syywINH2kai4L2hZTFxPeGBOlju58I1LBM+FVQkPaG9DRYoC5L6KgYT4vJRn+vDWvHq6t22gSRTJSRUY81mOgV1CCGLhIMF2WqixGGuEE/sbujMG8I0G8GC+7BctTY7NJOMghIYUAq9/uSnbdLFW3/FHdYjvt3cd5/FHXUnOSnp6fSB/LZVl0wI9DTqXSw91eNnFi+nYwC1UZ5Uu07u6eVxUrIM6rp57cztgfA9sV1i79Ourq5z3wJ7dzuRbzPkRFV0PcRk13aGqQuL5vIdYOJ2D07WC2LYwRvepSxruIzSfMTx2kA4O/OKS9NKrT7p5HQ8xQmHXhESlQBMnMbn/MNvrWqq370g7EQtO3uEoZjvE5yldU/zs45gGbHkUXZK2NoUHziXHAjmvUbJjrJQPKCertavdDGQO8lHFZxnxiwi9ExJrPWB1DJL1eSOwEXKYDvnjzW2q80KhEI7gIO+vCsO2g1+LU4X8mn/b/z7RhUhSDsyTOcyNQ02H/IvuVEJMbrnd9G2Y0lWpnSuMYu9ePg9qyWNrVUK98zjvEW13WaUsT2U8VhQlwseDZoQJBdj7DVbKUC4Sjri1TODO2aDIWvYzf/ufibPC/gjDgN+PFjN8B+mA4ClZgwcecV8MkHebEyfT8esf962d7HR71b2ExB+4=
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jessica@atomist.com
  password:
    secure: ecjHqr71u/3t6ohFPOsIlxKQSdA6W35fx18wqP9zgenBHDPUsKme/MAksb3pFDkcKNTUU6ur4TPprxkYI89dM4SKQQgVVjKZoavSmGNgxzyA+kTlRqMwSsImIqt779TcRDg02Y7Lb4aDEocDlUq7EUIEoDmeLfwK1DGZCnQ4KFe8Yq4jufJN8/8JFNT3dya5TTW3fc9mEyGDoEoPkPzXNAFsrNfZn52YJ2bLXZ9N6CYlQrzLEd8JDNJQZajGt8sLlUr6FXK+Fx9Qimoa8w5CpUmRX6fuMe50ohM6B1kjydjWjD2jAam7IkjknXuLtjp01eVjfdUtWzjBFlvp6HkvqF9LRGUl74JiKBd2h6EglOySdSFUbyoQoWmxvxCvetBkGliWl3tLnoEl1bM8w8tRvO0dRCDa06IaXn4sJGu6hGOaZMC0uKwupGlUoBn+kAgFzxPm7p4XMrC5o1GWhh/4tRTJoUozbsjmWtiIW4ZoZRShoMLNJONyueFRluP435Da9TWlTOAF8OWgF00Jt3llymEx1+2/eT/zRZ6R9ers/WFwakTjSOoW5CIE2jZ1Dr3ehrQ5L4S2zetv4YjZrB8P+5+tqaF8aCiYcOBzxeCofqu9OUL6CHapvu0lEjW0UiPVph0WktEX38GQAJp/a55VVtBUYoinMHnl8efbXWrjlUA=
  organization: atomist
  space: jessitron
  on:
    repo: atomist/tslint-automation
