dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
env:
  global:
  - secure: IhdbuzDS0zFqnUtm1k6syywINH2kai4L2hZTFxPeGBOlju58I1LBM+FVQkPaG9DRYoC5L6KgYT4vJRn+vDWvHq6t22gSRTJSRUY81mOgV1CCGLhIMF2WqixGGuEE/sbujMG8I0G8GC+7BctTY7NJOMghIYUAq9/uSnbdLFW3/FHdYjvt3cd5/FHXUnOSnp6fSB/LZVl0wI9DTqXSw91eNnFi+nYwC1UZ5Uu07u6eVxUrIM6rp57cztgfA9sV1i79Ourq5z3wJ7dzuRbzPkRFV0PcRk13aGqQuL5vIdYOJ2D07WC2LYwRvepSxruIzSfMTx2kA4O/OKS9NKrT7p5HQ8xQmHXhESlQBMnMbn/MNvrWqq370g7EQtO3uEoZjvE5yldU/zs45gGbHkUXZK2NoUHziXHAjmvUbJjrJQPKCertavdDGQO8lHFZxnxiwi9ExJrPWB1DJL1eSOwEXKYDvnjzW2q80KhEI7gIO+vCsO2g1+LU4X8mn/b/z7RhUhSDsyTOcyNQ02H/IvuVEJMbrnd9G2Y0lWpnSuMYu9ePg9qyWNrVUK98zjvEW13WaUsT2U8VhQlwseDZoQJBdj7DVbKUC4Sjri1TODO2aDIWvYzf/ufibPC/gjDgN+PFjN8B+mA4ClZgwcecV8MkHebEyfT8esf962d7HR71b2ExB+4=
  - secure: uZdWqL4YutijV6/bv8E8hnyvyHwVf7jPMz8QyuB2RNINPYBH0dVoVBN5I8XTfz7M5ZKFXWJcqKuEgEUp6wsqXKUy8yR7tEVaNQxN9gklUnT5LdMyk6C5nZSeKqPEPTukse6P8NvuQIlZt6cOFr9681ah9jZjSMoePXjdWkCGiCxrCARmubTKB0kPNDOe5EttSD5ptu87yWIN9IK8g2QZR350+x2yokdZrR+j2obN3k3/MbSTyFx30u0xA+H/0yi0f1JRvKEqOPMRnLWw6oLFhpTE6hFEC+3BtGzsYsLdoLXy1v9qjy/rE8z4OXbZBhM6HWHxNEil7DI00pKzLkvfU6g0Wgc1accpHIMJOvBoF63pE0JRQGumUkCJL5WZxI/0+sdRaXPUP0nJQI5/uOnJNWUYHVD2SndjZosopTL8wOpF+rLLZQ7cEibpPpZ+0HEU/xtb3ptVqOS196ebhGPlkrlWqBUNR4NEFjyTCK7nV04H/oy9ltOfwNx9kclWmWUHo7l/Up4vq+x4YrX8cmtZjiGlcehqeJePeHwB9G4ob5xTiTgmN9Gg7gQLK/scsxi/zcBj6VIgwl2woINZoRKXv+ePB4ukL7vDFHwLHCUN/Vpj8jJj3rN0oao+WIdrbd6vVpM+lv8jKF5/DebtIVdNOx5XJPqniBiVgDbqCN6TCRg=
  - secure: SPnOaH0lcYZux6TcOtF5xwIuVpcSUXAXhLnwHbqrjzG6oDjS3zWxlncG2MqRUBQyVj6iIq2x+EoEs4Lt2gYm9V/o+bF3vj8PA6sCYvTxnmXyq/I2+wo9x+Dta4H66WT9uOcehjmGs3yfcj5fU6Ki+TMC+J881h8xHl/6qxnKsC5sBRYaml9De/a9PujrxhGTmtud45l+fROTNtze6bR6YQSOkkncxI9yxZ1Ee1me9ggkrY3jeT02kowE9clhk4klHdDBs62JzaxiUgu++iPE0I5AYVjK4yu3M61lOt/9deDt9GpuFSk/GUtfhVs+clc7YZrXWguBBqK7a42fzykO5X8tPMIuA6d4gYCzN9GKLkoIH2cYqKCzpaXYFDunQWV80j/Fty/3hKkDG8UymQklj0ygL9XAAXlZTg/eRnP9iGCj6JvjoCSfn+jIKpVLsMA4OnRi4E9R71e01d89902IredfzgWRA/yJ4r7ItUVywUdByi2s3VIf+x2OUnr2sj8ScWc89vGYnK/lxrv8X0INcUM5SkHpP/E2wkcO6pjnXLgc7nlNMtiFAeMarE57nTtVMAYOV2n2woJwUvc7haqDiq2VVf/uNiGSjGem9e2pGOacUyjTyyBKEMqppobQ+TZBp1IwsVKWDlp1WGbJd6pCIHbhUhU65UDmFP/0eY2coCI=
  - secure: tEzoHPDGXXrxzeoB3DTu3fRISmQFKIBo3deFTQQuU4I+yQk9NrUmgMDKMq+j31+TwC/bFFONPlDoR1SFsNCsKI/S7a5X1OaUCQu5ZvTtZOzIwFbR7xDwJVQg6rYs/OJc1tP0XbCa5fYeP7uIitcCmfe17bR/HdqBjyG5j3UG28e8MipGvDiogZVNKoW9xiCmIZjKgmFwN+XRwi5VZYDE+0JfqHY/FQ19cDCecAsslXUPJH9Ua4VQv06fgYcqfPdxdmTBa7rKaMXe1Z/1COmRf6v3/GiyfvC+t+ACE3KUQr5rjbNKPYPQAGV+BoCGQunqh0pb/Dy8k55w/yh1OQb01wA8KEUuC6y322+vFFF7gC3lvusQ8qJtrlH9i9DtQ5+bq3K9R2BvWhugK4IZ2vUkhwHTwrFYALuphEihdBvsovSz0xsFQI1OVVM8iK+s3Z5kWqz8pyKQsEXEQ1K97pswFfVaXlhY2p786p7ErMr+s/OeRqqpbN+qS7Hpz6lPI1pNT55Riv/O853iJ4h3pdoRRZwIdDq6YGGJOq/G4CIIzKAsSpQ2YFCuwfBezo8pAzBwUOwleBPOBlyU85GN7ITREFG6s/76wgI1AQnR5DcK81PkmVk929ZhBUGki4rYzLvP33fPBN9kJti8cJfQJNhsNNvpM3crJCPIaJwQhKzUK6M=
script: bash scripts/travis-build.bash
services:
  - docker
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jessica@atomist.com
  password:
    secure: ecjHqr71u/3t6ohFPOsIlxKQSdA6W35fx18wqP9zgenBHDPUsKme/MAksb3pFDkcKNTUU6ur4TPprxkYI89dM4SKQQgVVjKZoavSmGNgxzyA+kTlRqMwSsImIqt779TcRDg02Y7Lb4aDEocDlUq7EUIEoDmeLfwK1DGZCnQ4KFe8Yq4jufJN8/8JFNT3dya5TTW3fc9mEyGDoEoPkPzXNAFsrNfZn52YJ2bLXZ9N6CYlQrzLEd8JDNJQZajGt8sLlUr6FXK+Fx9Qimoa8w5CpUmRX6fuMe50ohM6B1kjydjWjD2jAam7IkjknXuLtjp01eVjfdUtWzjBFlvp6HkvqF9LRGUl74JiKBd2h6EglOySdSFUbyoQoWmxvxCvetBkGliWl3tLnoEl1bM8w8tRvO0dRCDa06IaXn4sJGu6hGOaZMC0uKwupGlUoBn+kAgFzxPm7p4XMrC5o1GWhh/4tRTJoUozbsjmWtiIW4ZoZRShoMLNJONyueFRluP435Da9TWlTOAF8OWgF00Jt3llymEx1+2/eT/zRZ6R9ers/WFwakTjSOoW5CIE2jZ1Dr3ehrQ5L4S2zetv4YjZrB8P+5+tqaF8aCiYcOBzxeCofqu9OUL6CHapvu0lEjW0UiPVph0WktEX38GQAJp/a55VVtBUYoinMHnl8efbXWrjlUA=
  organization: atomist
  space: jessitron
  on:
    repo: atomist/tslint-automation
