dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
env:
  global:
  - secure: IhdbuzDS0zFqnUtm1k6syywINH2kai4L2hZTFxPeGBOlju58I1LBM+FVQkPaG9DRYoC5L6KgYT4vJRn+vDWvHq6t22gSRTJSRUY81mOgV1CCGLhIMF2WqixGGuEE/sbujMG8I0G8GC+7BctTY7NJOMghIYUAq9/uSnbdLFW3/FHdYjvt3cd5/FHXUnOSnp6fSB/LZVl0wI9DTqXSw91eNnFi+nYwC1UZ5Uu07u6eVxUrIM6rp57cztgfA9sV1i79Ourq5z3wJ7dzuRbzPkRFV0PcRk13aGqQuL5vIdYOJ2D07WC2LYwRvepSxruIzSfMTx2kA4O/OKS9NKrT7p5HQ8xQmHXhESlQBMnMbn/MNvrWqq370g7EQtO3uEoZjvE5yldU/zs45gGbHkUXZK2NoUHziXHAjmvUbJjrJQPKCertavdDGQO8lHFZxnxiwi9ExJrPWB1DJL1eSOwEXKYDvnjzW2q80KhEI7gIO+vCsO2g1+LU4X8mn/b/z7RhUhSDsyTOcyNQ02H/IvuVEJMbrnd9G2Y0lWpnSuMYu9ePg9qyWNrVUK98zjvEW13WaUsT2U8VhQlwseDZoQJBdj7DVbKUC4Sjri1TODO2aDIWvYzf/ufibPC/gjDgN+PFjN8B+mA4ClZgwcecV8MkHebEyfT8esf962d7HR71b2ExB+4=
  - DOCKER_USER=jessitron
  - secure: i6gaVZNx2bR8+b1BbRcIo4sb7LbGpkgAS/14YYG78jz10raoGccU0KEPM743pOhlYaqLtiaFApdX1Gff0Y3mlZRlv1jJEp8kICEEIBccGX42YiI2kDzo1q9E1xX02xZ9ZwXedreH6Ou0tGD4z1RXhYLtUIlDyRca+6o7LlY9WROCwbD50KqsBb2fo+kvfo7ebKEC3dbc5Iaim596y0BLJvO2rN4I1FjtL03pt3Rp3RfBGptqve1awfQduBf5Ods0PkmmNfCXr+kgVOdlrIHI0bfDL2SYy4Fc+tHyn+oWBPuPfz8tbAqkB/M+vdzLPRWuNuKzpqrCxDMRod40jJiTDwaSlrswm8VmXf4U2YP5sRhvHPJwheT5QKkcIPyXwDQiLoqWeJPFmpoApxyDcvGrIuA0qw3H/KtujRMBiLMsNapaNTLGwg6PPakkIeAFqCjjndN107XK/hSL/9mOZr+xej3lEgaIwCj7p+GnP/JxYjyvLIlaXgdzoaXdYQWVUUGwlQPUyESyKtSbXrqiLTAJYwNC0/m62drId0mFlStCAHFmU1yOCBFgXYHgXcppWh6SxtfFBrgROpp8ieWl5Xf6rKau9Cozbfd+nImdyI2UtGgnbt6/bNA1e2kywKMCBzuFyTJ5JCbnxRyHlbPS+s4p6+dPMxIdeMpPOgFe+s9rIEA=
script: bash scripts/travis-build.bash
services:
- docker
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
before_install:
- openssl aes-256-cbc -K $encrypted_c97baace1209_key -iv $encrypted_c97baace1209_iv
  -in linting-automation-48eb46756ce2.json.enc -out linting-automation-48eb46756ce2.json
  -d
