dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
env:
  global:
  - secure: IhdbuzDS0zFqnUtm1k6syywINH2kai4L2hZTFxPeGBOlju58I1LBM+FVQkPaG9DRYoC5L6KgYT4vJRn+vDWvHq6t22gSRTJSRUY81mOgV1CCGLhIMF2WqixGGuEE/sbujMG8I0G8GC+7BctTY7NJOMghIYUAq9/uSnbdLFW3/FHdYjvt3cd5/FHXUnOSnp6fSB/LZVl0wI9DTqXSw91eNnFi+nYwC1UZ5Uu07u6eVxUrIM6rp57cztgfA9sV1i79Ourq5z3wJ7dzuRbzPkRFV0PcRk13aGqQuL5vIdYOJ2D07WC2LYwRvepSxruIzSfMTx2kA4O/OKS9NKrT7p5HQ8xQmHXhESlQBMnMbn/MNvrWqq370g7EQtO3uEoZjvE5yldU/zs45gGbHkUXZK2NoUHziXHAjmvUbJjrJQPKCertavdDGQO8lHFZxnxiwi9ExJrPWB1DJL1eSOwEXKYDvnjzW2q80KhEI7gIO+vCsO2g1+LU4X8mn/b/z7RhUhSDsyTOcyNQ02H/IvuVEJMbrnd9G2Y0lWpnSuMYu9ePg9qyWNrVUK98zjvEW13WaUsT2U8VhQlwseDZoQJBdj7DVbKUC4Sjri1TODO2aDIWvYzf/ufibPC/gjDgN+PFjN8B+mA4ClZgwcecV8MkHebEyfT8esf962d7HR71b2ExB+4=
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
